# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.2.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.2.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zhenghu/GitHubWorking/C-Cli-Graphics

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zhenghu/GitHubWorking/C-Cli-Graphics

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.2.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.2.3/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhenghu/GitHubWorking/C-Cli-Graphics/CMakeFiles /Users/zhenghu/GitHubWorking/C-Cli-Graphics/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhenghu/GitHubWorking/C-Cli-Graphics/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Chess_Board

# Build rule for target.
Chess_Board: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Chess_Board
.PHONY : Chess_Board

# fast build rule for target.
Chess_Board/fast:
	$(MAKE) -f CMakeFiles/Chess_Board.dir/build.make CMakeFiles/Chess_Board.dir/build
.PHONY : Chess_Board/fast

#=============================================================================
# Target rules for targets named Linked_List_Test

# Build rule for target.
Linked_List_Test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Linked_List_Test
.PHONY : Linked_List_Test

# fast build rule for target.
Linked_List_Test/fast:
	$(MAKE) -f CMakeFiles/Linked_List_Test.dir/build.make CMakeFiles/Linked_List_Test.dir/build
.PHONY : Linked_List_Test/fast

#=============================================================================
# Target rules for targets named Mine_Sweeper

# Build rule for target.
Mine_Sweeper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Mine_Sweeper
.PHONY : Mine_Sweeper

# fast build rule for target.
Mine_Sweeper/fast:
	$(MAKE) -f CMakeFiles/Mine_Sweeper.dir/build.make CMakeFiles/Mine_Sweeper.dir/build
.PHONY : Mine_Sweeper/fast

#=============================================================================
# Target rules for targets named Plot_A_Circle

# Build rule for target.
Plot_A_Circle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Plot_A_Circle
.PHONY : Plot_A_Circle

# fast build rule for target.
Plot_A_Circle/fast:
	$(MAKE) -f CMakeFiles/Plot_A_Circle.dir/build.make CMakeFiles/Plot_A_Circle.dir/build
.PHONY : Plot_A_Circle/fast

#=============================================================================
# Target rules for targets named Util_Test

# Build rule for target.
Util_Test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Util_Test
.PHONY : Util_Test

# fast build rule for target.
Util_Test/fast:
	$(MAKE) -f CMakeFiles/Util_Test.dir/build.make CMakeFiles/Util_Test.dir/build
.PHONY : Util_Test/fast

src/examples/chessboard/chess_traceback.o: src/examples/chessboard/chess_traceback.c.o
.PHONY : src/examples/chessboard/chess_traceback.o

# target to build an object file
src/examples/chessboard/chess_traceback.c.o:
	$(MAKE) -f CMakeFiles/Chess_Board.dir/build.make CMakeFiles/Chess_Board.dir/src/examples/chessboard/chess_traceback.c.o
.PHONY : src/examples/chessboard/chess_traceback.c.o

src/examples/chessboard/chess_traceback.i: src/examples/chessboard/chess_traceback.c.i
.PHONY : src/examples/chessboard/chess_traceback.i

# target to preprocess a source file
src/examples/chessboard/chess_traceback.c.i:
	$(MAKE) -f CMakeFiles/Chess_Board.dir/build.make CMakeFiles/Chess_Board.dir/src/examples/chessboard/chess_traceback.c.i
.PHONY : src/examples/chessboard/chess_traceback.c.i

src/examples/chessboard/chess_traceback.s: src/examples/chessboard/chess_traceback.c.s
.PHONY : src/examples/chessboard/chess_traceback.s

# target to generate assembly for a file
src/examples/chessboard/chess_traceback.c.s:
	$(MAKE) -f CMakeFiles/Chess_Board.dir/build.make CMakeFiles/Chess_Board.dir/src/examples/chessboard/chess_traceback.c.s
.PHONY : src/examples/chessboard/chess_traceback.c.s

src/examples/mine_sweeper/mine_sweeper.o: src/examples/mine_sweeper/mine_sweeper.c.o
.PHONY : src/examples/mine_sweeper/mine_sweeper.o

# target to build an object file
src/examples/mine_sweeper/mine_sweeper.c.o:
	$(MAKE) -f CMakeFiles/Mine_Sweeper.dir/build.make CMakeFiles/Mine_Sweeper.dir/src/examples/mine_sweeper/mine_sweeper.c.o
.PHONY : src/examples/mine_sweeper/mine_sweeper.c.o

src/examples/mine_sweeper/mine_sweeper.i: src/examples/mine_sweeper/mine_sweeper.c.i
.PHONY : src/examples/mine_sweeper/mine_sweeper.i

# target to preprocess a source file
src/examples/mine_sweeper/mine_sweeper.c.i:
	$(MAKE) -f CMakeFiles/Mine_Sweeper.dir/build.make CMakeFiles/Mine_Sweeper.dir/src/examples/mine_sweeper/mine_sweeper.c.i
.PHONY : src/examples/mine_sweeper/mine_sweeper.c.i

src/examples/mine_sweeper/mine_sweeper.s: src/examples/mine_sweeper/mine_sweeper.c.s
.PHONY : src/examples/mine_sweeper/mine_sweeper.s

# target to generate assembly for a file
src/examples/mine_sweeper/mine_sweeper.c.s:
	$(MAKE) -f CMakeFiles/Mine_Sweeper.dir/build.make CMakeFiles/Mine_Sweeper.dir/src/examples/mine_sweeper/mine_sweeper.c.s
.PHONY : src/examples/mine_sweeper/mine_sweeper.c.s

src/examples/plot_a_circle/plot_a_circle.o: src/examples/plot_a_circle/plot_a_circle.c.o
.PHONY : src/examples/plot_a_circle/plot_a_circle.o

# target to build an object file
src/examples/plot_a_circle/plot_a_circle.c.o:
	$(MAKE) -f CMakeFiles/Plot_A_Circle.dir/build.make CMakeFiles/Plot_A_Circle.dir/src/examples/plot_a_circle/plot_a_circle.c.o
.PHONY : src/examples/plot_a_circle/plot_a_circle.c.o

src/examples/plot_a_circle/plot_a_circle.i: src/examples/plot_a_circle/plot_a_circle.c.i
.PHONY : src/examples/plot_a_circle/plot_a_circle.i

# target to preprocess a source file
src/examples/plot_a_circle/plot_a_circle.c.i:
	$(MAKE) -f CMakeFiles/Plot_A_Circle.dir/build.make CMakeFiles/Plot_A_Circle.dir/src/examples/plot_a_circle/plot_a_circle.c.i
.PHONY : src/examples/plot_a_circle/plot_a_circle.c.i

src/examples/plot_a_circle/plot_a_circle.s: src/examples/plot_a_circle/plot_a_circle.c.s
.PHONY : src/examples/plot_a_circle/plot_a_circle.s

# target to generate assembly for a file
src/examples/plot_a_circle/plot_a_circle.c.s:
	$(MAKE) -f CMakeFiles/Plot_A_Circle.dir/build.make CMakeFiles/Plot_A_Circle.dir/src/examples/plot_a_circle/plot_a_circle.c.s
.PHONY : src/examples/plot_a_circle/plot_a_circle.c.s

src/lib/graphics_lib.o: src/lib/graphics_lib.c.o
.PHONY : src/lib/graphics_lib.o

# target to build an object file
src/lib/graphics_lib.c.o:
	$(MAKE) -f CMakeFiles/Chess_Board.dir/build.make CMakeFiles/Chess_Board.dir/src/lib/graphics_lib.c.o
	$(MAKE) -f CMakeFiles/Mine_Sweeper.dir/build.make CMakeFiles/Mine_Sweeper.dir/src/lib/graphics_lib.c.o
	$(MAKE) -f CMakeFiles/Plot_A_Circle.dir/build.make CMakeFiles/Plot_A_Circle.dir/src/lib/graphics_lib.c.o
.PHONY : src/lib/graphics_lib.c.o

src/lib/graphics_lib.i: src/lib/graphics_lib.c.i
.PHONY : src/lib/graphics_lib.i

# target to preprocess a source file
src/lib/graphics_lib.c.i:
	$(MAKE) -f CMakeFiles/Chess_Board.dir/build.make CMakeFiles/Chess_Board.dir/src/lib/graphics_lib.c.i
	$(MAKE) -f CMakeFiles/Mine_Sweeper.dir/build.make CMakeFiles/Mine_Sweeper.dir/src/lib/graphics_lib.c.i
	$(MAKE) -f CMakeFiles/Plot_A_Circle.dir/build.make CMakeFiles/Plot_A_Circle.dir/src/lib/graphics_lib.c.i
.PHONY : src/lib/graphics_lib.c.i

src/lib/graphics_lib.s: src/lib/graphics_lib.c.s
.PHONY : src/lib/graphics_lib.s

# target to generate assembly for a file
src/lib/graphics_lib.c.s:
	$(MAKE) -f CMakeFiles/Chess_Board.dir/build.make CMakeFiles/Chess_Board.dir/src/lib/graphics_lib.c.s
	$(MAKE) -f CMakeFiles/Mine_Sweeper.dir/build.make CMakeFiles/Mine_Sweeper.dir/src/lib/graphics_lib.c.s
	$(MAKE) -f CMakeFiles/Plot_A_Circle.dir/build.make CMakeFiles/Plot_A_Circle.dir/src/lib/graphics_lib.c.s
.PHONY : src/lib/graphics_lib.c.s

src/lib/linked_list.o: src/lib/linked_list.c.o
.PHONY : src/lib/linked_list.o

# target to build an object file
src/lib/linked_list.c.o:
	$(MAKE) -f CMakeFiles/Linked_List_Test.dir/build.make CMakeFiles/Linked_List_Test.dir/src/lib/linked_list.c.o
.PHONY : src/lib/linked_list.c.o

src/lib/linked_list.i: src/lib/linked_list.c.i
.PHONY : src/lib/linked_list.i

# target to preprocess a source file
src/lib/linked_list.c.i:
	$(MAKE) -f CMakeFiles/Linked_List_Test.dir/build.make CMakeFiles/Linked_List_Test.dir/src/lib/linked_list.c.i
.PHONY : src/lib/linked_list.c.i

src/lib/linked_list.s: src/lib/linked_list.c.s
.PHONY : src/lib/linked_list.s

# target to generate assembly for a file
src/lib/linked_list.c.s:
	$(MAKE) -f CMakeFiles/Linked_List_Test.dir/build.make CMakeFiles/Linked_List_Test.dir/src/lib/linked_list.c.s
.PHONY : src/lib/linked_list.c.s

src/lib/math_plot.o: src/lib/math_plot.c.o
.PHONY : src/lib/math_plot.o

# target to build an object file
src/lib/math_plot.c.o:
	$(MAKE) -f CMakeFiles/Plot_A_Circle.dir/build.make CMakeFiles/Plot_A_Circle.dir/src/lib/math_plot.c.o
.PHONY : src/lib/math_plot.c.o

src/lib/math_plot.i: src/lib/math_plot.c.i
.PHONY : src/lib/math_plot.i

# target to preprocess a source file
src/lib/math_plot.c.i:
	$(MAKE) -f CMakeFiles/Plot_A_Circle.dir/build.make CMakeFiles/Plot_A_Circle.dir/src/lib/math_plot.c.i
.PHONY : src/lib/math_plot.c.i

src/lib/math_plot.s: src/lib/math_plot.c.s
.PHONY : src/lib/math_plot.s

# target to generate assembly for a file
src/lib/math_plot.c.s:
	$(MAKE) -f CMakeFiles/Plot_A_Circle.dir/build.make CMakeFiles/Plot_A_Circle.dir/src/lib/math_plot.c.s
.PHONY : src/lib/math_plot.c.s

src/lib/utils.o: src/lib/utils.c.o
.PHONY : src/lib/utils.o

# target to build an object file
src/lib/utils.c.o:
	$(MAKE) -f CMakeFiles/Chess_Board.dir/build.make CMakeFiles/Chess_Board.dir/src/lib/utils.c.o
	$(MAKE) -f CMakeFiles/Util_Test.dir/build.make CMakeFiles/Util_Test.dir/src/lib/utils.c.o
.PHONY : src/lib/utils.c.o

src/lib/utils.i: src/lib/utils.c.i
.PHONY : src/lib/utils.i

# target to preprocess a source file
src/lib/utils.c.i:
	$(MAKE) -f CMakeFiles/Chess_Board.dir/build.make CMakeFiles/Chess_Board.dir/src/lib/utils.c.i
	$(MAKE) -f CMakeFiles/Util_Test.dir/build.make CMakeFiles/Util_Test.dir/src/lib/utils.c.i
.PHONY : src/lib/utils.c.i

src/lib/utils.s: src/lib/utils.c.s
.PHONY : src/lib/utils.s

# target to generate assembly for a file
src/lib/utils.c.s:
	$(MAKE) -f CMakeFiles/Chess_Board.dir/build.make CMakeFiles/Chess_Board.dir/src/lib/utils.c.s
	$(MAKE) -f CMakeFiles/Util_Test.dir/build.make CMakeFiles/Util_Test.dir/src/lib/utils.c.s
.PHONY : src/lib/utils.c.s

src/test/linked_list_test.o: src/test/linked_list_test.c.o
.PHONY : src/test/linked_list_test.o

# target to build an object file
src/test/linked_list_test.c.o:
	$(MAKE) -f CMakeFiles/Linked_List_Test.dir/build.make CMakeFiles/Linked_List_Test.dir/src/test/linked_list_test.c.o
.PHONY : src/test/linked_list_test.c.o

src/test/linked_list_test.i: src/test/linked_list_test.c.i
.PHONY : src/test/linked_list_test.i

# target to preprocess a source file
src/test/linked_list_test.c.i:
	$(MAKE) -f CMakeFiles/Linked_List_Test.dir/build.make CMakeFiles/Linked_List_Test.dir/src/test/linked_list_test.c.i
.PHONY : src/test/linked_list_test.c.i

src/test/linked_list_test.s: src/test/linked_list_test.c.s
.PHONY : src/test/linked_list_test.s

# target to generate assembly for a file
src/test/linked_list_test.c.s:
	$(MAKE) -f CMakeFiles/Linked_List_Test.dir/build.make CMakeFiles/Linked_List_Test.dir/src/test/linked_list_test.c.s
.PHONY : src/test/linked_list_test.c.s

src/test/util_test.o: src/test/util_test.c.o
.PHONY : src/test/util_test.o

# target to build an object file
src/test/util_test.c.o:
	$(MAKE) -f CMakeFiles/Util_Test.dir/build.make CMakeFiles/Util_Test.dir/src/test/util_test.c.o
.PHONY : src/test/util_test.c.o

src/test/util_test.i: src/test/util_test.c.i
.PHONY : src/test/util_test.i

# target to preprocess a source file
src/test/util_test.c.i:
	$(MAKE) -f CMakeFiles/Util_Test.dir/build.make CMakeFiles/Util_Test.dir/src/test/util_test.c.i
.PHONY : src/test/util_test.c.i

src/test/util_test.s: src/test/util_test.c.s
.PHONY : src/test/util_test.s

# target to generate assembly for a file
src/test/util_test.c.s:
	$(MAKE) -f CMakeFiles/Util_Test.dir/build.make CMakeFiles/Util_Test.dir/src/test/util_test.c.s
.PHONY : src/test/util_test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Plot_A_Circle"
	@echo "... Linked_List_Test"
	@echo "... Util_Test"
	@echo "... Mine_Sweeper"
	@echo "... Chess_Board"
	@echo "... src/examples/chessboard/chess_traceback.o"
	@echo "... src/examples/chessboard/chess_traceback.i"
	@echo "... src/examples/chessboard/chess_traceback.s"
	@echo "... src/examples/mine_sweeper/mine_sweeper.o"
	@echo "... src/examples/mine_sweeper/mine_sweeper.i"
	@echo "... src/examples/mine_sweeper/mine_sweeper.s"
	@echo "... src/examples/plot_a_circle/plot_a_circle.o"
	@echo "... src/examples/plot_a_circle/plot_a_circle.i"
	@echo "... src/examples/plot_a_circle/plot_a_circle.s"
	@echo "... src/lib/graphics_lib.o"
	@echo "... src/lib/graphics_lib.i"
	@echo "... src/lib/graphics_lib.s"
	@echo "... src/lib/linked_list.o"
	@echo "... src/lib/linked_list.i"
	@echo "... src/lib/linked_list.s"
	@echo "... src/lib/math_plot.o"
	@echo "... src/lib/math_plot.i"
	@echo "... src/lib/math_plot.s"
	@echo "... src/lib/utils.o"
	@echo "... src/lib/utils.i"
	@echo "... src/lib/utils.s"
	@echo "... src/test/linked_list_test.o"
	@echo "... src/test/linked_list_test.i"
	@echo "... src/test/linked_list_test.s"
	@echo "... src/test/util_test.o"
	@echo "... src/test/util_test.i"
	@echo "... src/test/util_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

